CREATE TABLE IF NOT EXISTS commerce_merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL, code VARCHAR(32) NOT NULL,
    contact_name VARCHAR(30) NOT NULL, contact_mobile VARCHAR(20) NOT NULL,
    default_store_name VARCHAR(64) NOT NULL, default_store_code VARCHAR(32) NOT NULL,
    status TINYINT NOT NULL, owner_user_id BIGINT, reviewer_user_id BIGINT,
    review_time TIMESTAMP, reject_reason VARCHAR(255),
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_merchant_code UNIQUE (code),
    CONSTRAINT uk_commerce_merchant_default_store_code UNIQUE (default_store_code),
    CONSTRAINT uk_commerce_merchant_owner_user UNIQUE (owner_user_id)
);
CREATE TABLE IF NOT EXISTS commerce_store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL, name VARCHAR(64) NOT NULL, code VARCHAR(32) NOT NULL,
    description VARCHAR(500), contact_name VARCHAR(30) NOT NULL, contact_mobile VARCHAR(20) NOT NULL,
    status TINYINT NOT NULL, creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_store_merchant UNIQUE (merchant_id), CONSTRAINT uk_commerce_store_code UNIQUE (code),
    CONSTRAINT uk_commerce_store_id_merchant UNIQUE (id, merchant_id)
);
CREATE TABLE IF NOT EXISTS commerce_merchant_operator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL, user_id BIGINT NOT NULL, operator_type TINYINT NOT NULL, status TINYINT NOT NULL,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_operator_merchant_user UNIQUE (merchant_id, user_id),
    CONSTRAINT uk_commerce_operator_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS commerce_product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    code VARCHAR(32) NOT NULL,
    name VARCHAR(64) NOT NULL,
    image_url VARCHAR(1024),
    sort INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_product_category_code UNIQUE (code),
    CONSTRAINT fk_commerce_product_category_parent FOREIGN KEY (parent_id)
        REFERENCES commerce_product_category (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_commerce_product_category_status CHECK (status IN (0, 1)),
    CONSTRAINT chk_commerce_product_category_sort CHECK (sort >= 0)
);

CREATE TABLE IF NOT EXISTS commerce_product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL, store_id BIGINT NOT NULL, category_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL, name VARCHAR(128) NOT NULL, subtitle VARCHAR(255),
    main_image_url VARCHAR(1024) NOT NULL, image_urls VARCHAR(4096), description CLOB NOT NULL,
    audit_status TINYINT NOT NULL DEFAULT 0, sale_status TINYINT NOT NULL DEFAULT 0,
    reviewer_user_id BIGINT, review_time TIMESTAMP, reject_reason VARCHAR(255),
    sort INT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_product_id_merchant UNIQUE (id, merchant_id),
    CONSTRAINT uk_commerce_product_merchant_code UNIQUE (merchant_id, code),
    CONSTRAINT fk_commerce_product_merchant FOREIGN KEY (merchant_id)
        REFERENCES commerce_merchant (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_commerce_product_store_owner FOREIGN KEY (store_id, merchant_id)
        REFERENCES commerce_store (id, merchant_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_commerce_product_category FOREIGN KEY (category_id)
        REFERENCES commerce_product_category (id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_commerce_product_audit_status CHECK (audit_status IN (0, 1, 2, 3)),
    CONSTRAINT chk_commerce_product_sale_status CHECK (sale_status IN (0, 1)),
    CONSTRAINT chk_commerce_product_sale_requires_approval CHECK (sale_status = 0 OR audit_status = 2),
    CONSTRAINT chk_commerce_product_sort CHECK (sort >= 0),
    CONSTRAINT chk_commerce_product_review_metadata CHECK (
        (audit_status IN (0, 1) AND reviewer_user_id IS NULL AND review_time IS NULL AND reject_reason IS NULL)
        OR (audit_status = 2 AND reviewer_user_id IS NOT NULL AND review_time IS NOT NULL AND reject_reason IS NULL)
        OR (audit_status = 3 AND reviewer_user_id IS NOT NULL AND review_time IS NOT NULL
            AND reject_reason IS NOT NULL AND CHAR_LENGTH(TRIM(reject_reason)) > 0)
    )
);

CREATE TABLE IF NOT EXISTS commerce_product_sku (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL, merchant_id BIGINT NOT NULL, code VARCHAR(64) NOT NULL,
    specification_values VARCHAR(4096), image_url VARCHAR(1024),
    price BIGINT NOT NULL, market_price BIGINT, stock INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0, sort INT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_product_sku_merchant_code UNIQUE (merchant_id, code),
    CONSTRAINT uk_commerce_product_sku_id_product UNIQUE (id, product_id),
    CONSTRAINT fk_commerce_product_sku_owner FOREIGN KEY (product_id, merchant_id)
        REFERENCES commerce_product (id, merchant_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_commerce_product_sku_price CHECK (price >= 0),
    CONSTRAINT chk_commerce_product_sku_market_price CHECK (market_price IS NULL OR market_price >= 0),
    CONSTRAINT chk_commerce_product_sku_stock CHECK (stock >= 0),
    CONSTRAINT chk_commerce_product_sku_status CHECK (status IN (0, 1)),
    CONSTRAINT chk_commerce_product_sku_sort CHECK (sort >= 0)
);

CREATE INDEX IF NOT EXISTS idx_commerce_product_category_parent_status_sort
    ON commerce_product_category (parent_id, status, sort);
CREATE INDEX IF NOT EXISTS idx_commerce_product_merchant_state_time
    ON commerce_product (merchant_id, audit_status, sale_status, create_time);
CREATE INDEX IF NOT EXISTS idx_commerce_product_store_state_time
    ON commerce_product (store_id, audit_status, sale_status, create_time);
CREATE INDEX IF NOT EXISTS idx_commerce_product_public_category
    ON commerce_product (category_id, audit_status, sale_status, sort, id);
CREATE INDEX IF NOT EXISTS idx_commerce_product_sku_product_status_sort
    ON commerce_product_sku (product_id, status, sort, id);

-- Minimal System identity tables used by the shared-transaction rollback test.
CREATE TABLE IF NOT EXISTS system_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL DEFAULT '',
    nickname VARCHAR(30) NOT NULL,
    mobile VARCHAR(11) DEFAULT '',
    status TINYINT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE, tenant_id BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS system_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, role_id BIGINT NOT NULL,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE, tenant_id BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS commerce_cart_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_user_id BIGINT NOT NULL, product_id BIGINT NOT NULL, sku_id BIGINT NOT NULL,
    quantity INT NOT NULL, selected BOOLEAN NOT NULL DEFAULT TRUE,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_commerce_cart_user_sku UNIQUE (member_user_id, sku_id),
    CONSTRAINT fk_commerce_cart_sku_product FOREIGN KEY (sku_id, product_id)
        REFERENCES commerce_product_sku (id, product_id),
    CONSTRAINT chk_commerce_cart_quantity CHECK (quantity BETWEEN 1 AND 99),
    CONSTRAINT chk_commerce_cart_selected CHECK (selected IN (FALSE, TRUE))
);
