<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.boot</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>curmerce-services</artifactId>
    <packaging>pom</packaging>
    <name>${project.artifactId}</name>
    <description>Curmerce independently deployable service applications</description>
    <modules>
        <module>curmerce-cloud-api</module>
        <module>curmerce-gateway</module>
        <module>curmerce-community-service</module>
        <module>curmerce-agent-service</module>
    </modules>
</project>
