"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Notice } from "@/components/notice";
import { communityApi } from "@/lib/api/community";
import { CurmerceApiError, assetUrl } from "@/lib/api/client";
import { formatDateTime, formatMoney } from "@/lib/format";
import type { CommunityComment, CommunityPost } from "@/lib/types/api";

export default function CommunityPostPage() {
  const params = useParams<{ id: string }>(); const router = useRouter();
  const [post, setPost] = useState<CommunityPost | null>(null); const [comments, setComments] = useState<CommunityComment[]>([]); const [comment, setComment] = useState(""); const [reportReason, setReportReason] = useState(""); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function load(id: number) { try { const [nextPost, nextComments] = await Promise.all([communityApi.get(id), communityApi.pageComments(id)]); setPost(nextPost); setComments(nextComments.list ?? []); } catch (cause) { setError(cause instanceof CurmerceApiError ? cause.message : "帖子加载失败"); } }
  useEffect(() => { const id = Number(params.id); if (id > 0) void load(id); }, [params.id]);
  async function toggle(type: number, active: boolean) { if (!post) return; try { await communityApi.reaction({ postId: post.id, type, active }); setPost(await communityApi.get(post.id)); } catch (cause) { if (cause instanceof CurmerceApiError && cause.status === 401) router.push("/login"); else setError(cause instanceof CurmerceApiError ? cause.message : "操作失败"); } }
  async function toggleFollow() { if (!post) return; try { await communityApi.follow({ userId: post.authorUserId, active: !post.followingAuthor }); setPost(await communityApi.get(post.id)); } catch (cause) { if (cause instanceof CurmerceApiError && cause.status === 401) router.push("/login"); else setError(cause instanceof CurmerceApiError ? cause.message : "关注操作失败"); } }
  async function addComment() { if (!post || !comment.trim()) return; try { await communityApi.comment({ postId: post.id, content: comment.trim() }); setComment(""); setComments((await communityApi.pageComments(post.id)).list ?? []); setMessage("评论已发布"); } catch (cause) { setError(cause instanceof CurmerceApiError ? cause.message : "评论失败"); } }
  async function report() { if (!post || !reportReason.trim()) return; try { await communityApi.report({ postId: post.id, reason: reportReason.trim() }); setReportReason(""); setMessage("举报已提交，等待审核"); } catch (cause) { setError(cause instanceof CurmerceApiError ? cause.message : "举报失败"); } }
  if (!post) return <section className="content-section"><Notice>{error ?? "帖子加载中…"}</Notice></section>;
  return <section className="content-section community-detail"><div className="community-detail__back"><Link href="/community">← 返回社区</Link><Link href="/catalog">去逛商城 →</Link></div>{message ? <Notice tone="success">{message}</Notice> : null}{error ? <Notice>{error}</Notice> : null}<article className="community-detail__article"><div className="community-card__meta"><strong>{post.authorNickname || `用户 ${post.authorUserId}`}</strong><span>{formatDateTime(post.createTime)}</span></div><h1>{post.title}</h1><div className="community-topics">{post.topics?.map((topic) => <span className="tag" key={topic.id}>#{topic.name}</span>)}</div><p className="community-detail__content">{post.content}</p>{post.mediaUrls?.length ? <div className="community-media-grid">{post.mediaUrls.map((url) => <img key={url} src={assetUrl(url) ?? ""} alt="帖子配图" />)}</div> : null}<div className="community-actions"><button className={`button ${post.liked ? "button--primary" : "button--secondary"}`} type="button" onClick={() => void toggle(1, !post.liked)}>♥ {post.likeCount}</button><button className={`button ${post.favorited ? "button--primary" : "button--secondary"}`} type="button" onClick={() => void toggle(2, !post.favorited)}>★ {post.favoriteCount}</button><button className="button button--secondary" type="button" onClick={() => void toggleFollow()}>{post.followingAuthor ? "已关注作者" : "关注作者"}</button></div>{post.products?.length ? <div className="community-products"><h2>帖子中提到的商品</h2><div className="product-grid">{post.products.map((product) => <Link className="product-card" href={`/products/${product.id}`} key={product.id}><div className="product-card__body"><span className="product-card__store">{product.storeName}</span><strong className="product-card__name">{product.name}</strong><div className="product-card__footer"><strong>{formatMoney(product.minPrice)}</strong><span>查看商品 →</span></div></div></Link>)}</div></div> : null}</article><section className="community-comments"><div className="panel-heading"><h2>评论</h2><span>{comments.length} 条</span></div><div className="comment-list">{comments.map((item) => <div className="comment-item" key={item.id}><strong>{item.authorNickname || `用户 ${item.authorUserId}`}</strong><span>{formatDateTime(item.createTime)}</span><p>{item.content}</p></div>)}</div><div className="comment-compose"><textarea rows={3} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="写下你的看法" /><button className="button button--primary" type="button" onClick={() => void addComment()}>发表评论</button></div></section><section className="community-report"><h2>举报内容</h2><div className="comment-compose"><input value={reportReason} onChange={(event) => setReportReason(event.target.value)} placeholder="请说明举报原因" /><button className="button button--secondary" type="button" onClick={() => void report()}>提交举报</button></div></section></section>;
}
