"use client";
import { FormEvent, Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Notice } from "@/components/notice";
import { communityApi } from "@/lib/api/community";
import { CurmerceApiError } from "@/lib/api/client";

function CommunityCreateForm() {
  const router = useRouter(); const searchParams = useSearchParams(); const editId = Number(searchParams.get("id") ?? 0);
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [topics, setTopics] = useState(""); const [mediaUrls, setMediaUrls] = useState<string[]>([]); const [productIds, setProductIds] = useState(""); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false);
  useEffect(() => { if (!editId) return; void communityApi.get(editId).then((post) => { setTitle(post.title); setContent(post.content); setTopics(post.topics?.map((topic) => topic.name).join(",") ?? ""); setMediaUrls(post.mediaUrls ?? []); setProductIds(post.products?.map((product) => String(product.id)).join(",") ?? ""); }).catch((cause) => setError(cause instanceof CurmerceApiError ? cause.message : "草稿加载失败")); }, [editId]);
  function payload() { return { title, content, topics: topics.split(",").map((value) => value.trim()).filter(Boolean), mediaUrls, productIds: productIds.split(",").map((value) => Number(value.trim())).filter((value) => Number.isInteger(value) && value > 0) }; }
  async function save(submitAfter: boolean) { setBusy(true); setError(null); setMessage(null); try { const id = editId || await communityApi.create(payload()); if (editId) await communityApi.update({ id: editId, ...payload() }); if (submitAfter) { await communityApi.submit(id); router.push(`/community/${id}`); } else { setMessage("草稿已保存"); if (!editId) router.replace(`/community/create?id=${id}`); } } catch (cause) { setError(cause instanceof CurmerceApiError ? cause.message : "帖子保存失败"); } finally { setBusy(false); } }
  async function onSubmit(event: FormEvent) { event.preventDefault(); await save(true); }
  async function upload(event: React.ChangeEvent<HTMLInputElement>) { const files = Array.from(event.target.files ?? []); if (!files.length) return; setUploading(true); setError(null); try { const urls = await Promise.all(files.map((file) => communityApi.uploadMedia(file))); setMediaUrls((current) => [...current, ...urls]); } catch (cause) { setError(cause instanceof CurmerceApiError ? cause.message : "图片上传失败"); } finally { setUploading(false); event.target.value = ""; } }
  return <section className="content-section community-editor"><div className="section-heading"><div><p className="eyebrow">COMMUNITY · WRITE</p><h1>{editId ? "编辑社区帖子" : "发布一篇帖子"}</h1><p>先保存草稿，确认内容后再提交到公开内容流。</p></div></div>{message ? <Notice tone="success">{message}</Notice> : null}{error ? <Notice>{error}</Notice> : null}<form className="form-card" onSubmit={onSubmit}><label className="field"><span>标题</span><input required maxLength={120} value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="field"><span>正文</span><textarea required maxLength={100000} rows={12} value={content} onChange={(event) => setContent(event.target.value)} /></label><label className="field"><span>话题（逗号分隔）</span><input value={topics} onChange={(event) => setTopics(event.target.value)} placeholder="例如 咖啡,居家" /></label><label className="field"><span>上传配图</span><input accept="image/*" multiple type="file" onChange={upload} disabled={uploading} />{uploading ? <small>上传中…</small> : null}<div className="upload-preview">{mediaUrls.map((url) => <img key={url} src={url.startsWith("http") ? url : `${process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:48080"}${url.startsWith("/") ? url : `/${url}`}`} alt="已上传配图" />)}</div></label><label className="field"><span>关联商品编号（逗号分隔）</span><input value={productIds} onChange={(event) => setProductIds(event.target.value)} placeholder="例如 18,19" /></label><div className="inline-actions"><button className="button button--secondary" disabled={busy || uploading} type="button" onClick={() => void save(false)}>保存草稿</button><button className="button button--primary" disabled={busy || uploading} type="submit">{busy ? "处理中…" : "保存并提交"}</button></div></form></section>;
}

export default function CommunityCreatePage() {
  return <Suspense fallback={<section className="content-section"><p className="empty-state">编辑器加载中…</p></section>}><CommunityCreateForm /></Suspense>;
}
