CREATE TABLE IF NOT EXISTS commerce_merchant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL, code VARCHAR(32) NOT NULL,
    contact_name VARCHAR(30) NOT NULL, contact_mobile VARCHAR(20) NOT NULL,
    default_store_name VARCHAR(64) NOT NULL, default_store_code VARCHAR(32) NOT NULL,
    status TINYINT NOT NULL, owner_user_id BIGINT, reviewer_user_id BIGINT,
    review_time TIMESTAMP, reject_reason VARCHAR(255),
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_merchant_code UNIQUE (code),
    CONSTRAINT uk_commerce_merchant_default_store_code UNIQUE (default_store_code),
    CONSTRAINT uk_commerce_merchant_owner_user UNIQUE (owner_user_id)
);
CREATE TABLE IF NOT EXISTS commerce_store (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL, name VARCHAR(64) NOT NULL, code VARCHAR(32) NOT NULL,
    description VARCHAR(500), contact_name VARCHAR(30) NOT NULL, contact_mobile VARCHAR(20) NOT NULL,
    status TINYINT NOT NULL, creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_store_merchant UNIQUE (merchant_id), CONSTRAINT uk_commerce_store_code UNIQUE (code)
);
CREATE TABLE IF NOT EXISTS commerce_merchant_operator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL, user_id BIGINT NOT NULL, operator_type TINYINT NOT NULL, status TINYINT NOT NULL,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, deleted BOOLEAN DEFAULT FALSE,
    CONSTRAINT uk_commerce_operator_merchant_user UNIQUE (merchant_id, user_id),
    CONSTRAINT uk_commerce_operator_user UNIQUE (user_id)
);

-- Minimal System identity tables used by the shared-transaction rollback test.
CREATE TABLE IF NOT EXISTS system_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL DEFAULT '',
    nickname VARCHAR(30) NOT NULL,
    mobile VARCHAR(11) DEFAULT '',
    status TINYINT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE, tenant_id BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS system_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL, role_id BIGINT NOT NULL,
    creator VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT FALSE, tenant_id BIGINT NOT NULL DEFAULT 0
);
